# Generated by Django 5.2.8 on 2025-11-26 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成交价')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已付保证金')),
                ('earnest_money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='定金')),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='手续费')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '已取消'), (3, '已完成')], default=0, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_orders', to=settings.AUTH_USER_MODEL, verbose_name='买家')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_orders', to=settings.AUTH_USER_MODEL, verbose_name='卖家')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionsession', verbose_name='竞拍场次')),
            ],
            options={
                'verbose_name': '拍卖订单',
                'verbose_name_plural': '拍卖订单',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='BidRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='出价金额')),
                ('bid_time', models.DateTimeField(auto_now_add=True, verbose_name='出价时间')),
                ('is_leading', models.BooleanField(default=False, verbose_name='是否领先')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='竞买人')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auctionsession', verbose_name='所属场次')),
            ],
            options={
                'verbose_name': '竞价记录',
                'verbose_name_plural': '竞价记录',
                'ordering': ['-bid_price'],
            },
        ),
    ]
