# Generated by Django 5.2.8 on 2025-11-26 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='变动金额')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='变动后余额')),
                ('trans_type', models.CharField(choices=[('topup', '充值'), ('payment', '支付订单'), ('income', '出售收入'), ('refund', '退款'), ('service_fee', '服务费扣除')], max_length=20, verbose_name='交易类型')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='交易时间')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trades.auctionorder', verbose_name='关联订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '资金流水',
                'verbose_name_plural': '资金流水',
                'ordering': ['-create_time'],
            },
        ),
    ]
