# Generated by Django 5.2.8 on 2025-11-27 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='保证金金额')),
                ('status', models.CharField(choices=[('paid', '已缴纳'), ('refunded', '已退回'), ('deducted', '已扣除(违约)'), ('transferred', '已转货款')], default='paid', max_length=20, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='缴纳时间')),
                ('auction_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.auctionitem', verbose_name='关联拍品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='缴纳用户')),
            ],
            options={
                'verbose_name': '拍卖保证金',
                'verbose_name_plural': '拍卖保证金',
                'unique_together': {('user', 'auction_item')},
            },
        ),
    ]
