# Generated by Django 5.2.8 on 2025-11-26 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '拍品分类',
                'verbose_name_plural': '拍品分类',
            },
        ),
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='拍品名称')),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='起拍价')),
                ('reserve_price', models.DecimalField(decimal_places=2, help_text='低于此价格不成交', max_digits=10, verbose_name='保留价')),
                ('deposit_ratio', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='保证金比例(%)')),
                ('earnest_money_ratio', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='定金比例(%)')),
                ('image_paths', models.TextField(help_text='存储多张图片路径，用逗号分隔', verbose_name='图片路径')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '待审核'), (1, '待开拍'), (2, '竞拍中'), (3, '已成交'), (4, '流拍')], default=0, verbose_name='状态')),
                ('reject_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='驳回原因')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='卖家')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemcategory', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '拍品',
                'verbose_name_plural': '拍品',
                'db_table': 'auction_item',
                'ordering': ['-create_time'],
            },
        ),
    ]
