# Generated by Django 5.2.8 on 2026-03-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='description',
            field=models.TextField(blank=True, help_text='卖家对拍品的详细文字描述（如瑕疵、年份等）', null=True, verbose_name='拍品描述'),
        ),
    ]
