# Generated by Django 5.2.8 on 2026-03-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auctionitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='auction_type',
            field=models.CharField(choices=[('increase', '增价拍卖'), ('decrease', '减价拍卖')], default='increase', max_length=20, verbose_name='拍卖类型'),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='bottom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='仅减价拍卖有效', max_digits=10, null=True, verbose_name='底价'),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='price_step',
            field=models.DecimalField(decimal_places=2, default=0, help_text='增价为最小加价，减价为每次降价', max_digits=10, verbose_name='加/降价幅度'),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='reduce_interval',
            field=models.IntegerField(blank=True, default=0, help_text='仅减价拍卖有效', null=True, verbose_name='降价间隔(秒)'),
        ),
    ]
