# Generated by Django 5.2.8 on 2026-03-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auctionitem_auction_type_auctionitem_bottom_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='expected_end_time',
            field=models.DateTimeField(blank=True, help_text='由卖家发布时指定', null=True, verbose_name='期望结束时间'),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='expected_start_time',
            field=models.DateTimeField(blank=True, help_text='由卖家发布时指定', null=True, verbose_name='期望开拍时间'),
        ),
    ]
