# Generated by Django 5.2.8 on 2025-11-26 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='场次名称')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('auction_type', models.CharField(choices=[('increase', '增价拍卖'), ('decrease', '减价拍卖')], default='increase', max_length=20, verbose_name='拍卖类型')),
                ('price_step', models.DecimalField(decimal_places=2, help_text='增价为最小加价，减价为每次降价', max_digits=10, verbose_name='加/降价幅度')),
                ('reduce_interval', models.IntegerField(blank=True, default=0, help_text='仅减价拍卖有效', null=True, verbose_name='降价间隔(秒)')),
                ('bottom_price', models.DecimalField(blank=True, decimal_places=2, help_text='仅减价拍卖有效', max_digits=10, null=True, verbose_name='底价')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已结束')], default=0, verbose_name='状态')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='当前价格')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='items.auctionitem', verbose_name='关联拍品')),
            ],
            options={
                'verbose_name': '拍卖场次',
                'verbose_name_plural': '拍卖场次',
                'db_table': 'auction_session',
                'ordering': ['start_time'],
            },
        ),
    ]
